# Numpy
## Ejercicios prácticos

---
### Utiliza Python y Numpy para realizar las siguientes operaciones:
1. Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.
2. Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
10. Crea un arreglo que contenga los números pares entre 30 y 70.
11. Crea una matriz identidad de 3x3.
12. Genera un número aleatorio entre 0 y 1.
13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

In [1]:
import numpy as np

In [2]:
# ejercicio 1 import numpy as np

a = np.array([1, 2, 3, 4])
np.all(a != 0)
True

In [3]:
# ejercicio 2
a = np.array([0, 0, 2, 0])
np.any(a != 0)
True

In [4]:
# ejercicio 3

a = np.array([1, 2, np.nan, np.inf])
np.any(np.isinf(a))   # True → hay infinitos
np.any(np.isnan(a))   # True → hay NaN

In [6]:
# ejercicio 4
a = np.array([1, 2, np.inf])
np.isinf(a)
#Valores infinitos
[False, False, False, True]

In [ ]:
# ejercicio 5
a = np.array([1, np.nan, 3])
np.any(np.isnan(a))
True

In [ ]:
# ejercicio 6
a = np.array([1, 3, 5])
b = np.array([2, 3, 4])
a > b
[False, False, True]
a >= b
[False, True, True]
a < b
[True, False, False]
a <= b
[True, True, False]

In [ ]:
# ejercicio 7
a = np.array([1, 7, 13, 105])

print("Arreglo:", a)
print("Memoria (bytes):", a.nbytes)
Memoria (bytes): 32

In [ ]:
#ejercio 8
ceros = np.zeros(10)
unos = np.ones(10)
cincos = np.full(10, 5)

print("Ceros :", ceros)
print("Unos  :", unos)
print("Cincos:", cincos)
Ceros : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Unos  : [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Cincos: [5 5 5 5 5 5 5 5 5 5]

In [ ]:
#Ejercicio 9
arr_9 = np.arange(30, 71)
print("9 :", arr_9)
9 : [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]

In [ ]:
#Ejercicio 10
arr_10 = np.arange(30, 71, 2)
print("10:", arr_10)
10: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]

In [ ]:
#Ejercicio 11
arr_11 = np.eye(3)
print("11:\n", arr_11)
11:

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

In [ ]:
#Ejercicio 12
arr_12 = np.random.rand()
print("12:", arr_12)
12: 0.9490394751090104

In [ ]:
#Ejercicio 13
arr_13 = np.random.randn(15)
print("13:", arr_13)
13: [ 0.12800679 -0.66412026 -0.37485568 0.55589797 1.30712572 -1.24178221 -0.37122224 -0.29996105 -0.48641319 -1.72323534 -0.80818714 -0.17690313 -0.10796599 0.75186891 0.74440872]

In [ ]:
#Ejercicio 14
arr_14 = np.arange(15, 56)
arr_14_slice = arr_14[1:-1]
print("14:", arr_14_slice)
14: [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]

In [ ]:
#Ejercicio 15
arr_15 = np.linspace(5, 50, 10)
print("15:", arr_15)
15: [ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]

In [ ]:
#Ejercicio 16
arr_16 = np.arange(0, 21)
arr_16[9:16] *= -1
print("16:", arr_16)
16: [ 0 1 2 3 4 5 6 7 8 -9 -10 -11 -12 -13 -14 -15 16 17 18 19 20]

In [ ]:
#Ejercicio 17
a = np.array([1, 2, 3])
list_17 = a.tolist()
print("17:", list_17)
17: [1, 2, 3]

In [ ]:
#Ejercicio 18
l = [1, 2, 3]
arr_18 = np.array(l)
print("18:", arr_18)
18: [1 2 3]

In [ ]:
#Ejercicio 19
m_19 = np.array([[1, 2], [3, 4]])
pares_19 = (m_19 % 2 == 0)
print("19:\n", pares_19)
19:

 [[False  True]
 [False  True]]

In [ ]:
#Ejercicio 20
m_20 = np.array([[1, 2, 3], [4, 5, 6]])
filas, columnas = m_20.shape
print("20: filas =", filas, ", columnas =", columnas)
20: filas = 2 , columnas = 3